type: "q-e"
url: amqp://guest:guest@rabbitmq:5672/
input: query_results
output: e_entry
exchange_type: topic
prefetch: 300
durable: true
auto_delete: false
exclusive: false
no_wait: false
internal: false

server_host: "0.0.0.0"
server_port: 8080
