broker:
  type: e-e
  input:
    exchange:
      name: e_q3_agg
      type: direct
    queue:
      name: q_q3_aggregator
  output:
    exchange:
      name: e_q3_avg
      type: fanout

worker:
  type: "Aggregator"
  params:
    type: avg
    field: Amount
    group:
      format: Format
  sync_eof:
    retries_base_delay: 0.5
    retries_step_delay: 0.5
    max_retries: 5
