broker:
  type: e-q
  url: amqp://guest:guest@rabbitmq:5672/
  input: e_q345_cleaner
  input_queue: q_q3_avg_cleaner
  output: q_q3_router
  exchange_type: topic
  input_keys:
    - tx.usd
  prefetch: 300
  durable: true
  auto_delete: false
  exclusive: false
  no_wait: false
  internal: false

worker:
  type: "Cleaner"
  params:
    field:
      - "dest"
  query: 3
  sync_eof:
    - retries_base_delay: 0.5
    - retries_step_delay: 0.5
    - max_retries: 5
