name: money-laundering-analysis
services:
  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: gateway
    environment:
      - LOG_LEVEL=debug
    networks:
      - money-laundering-analysis-net
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
      - RABBITMQ_LOG_LEVELS=error
    networks:
      - money-laundering-analysis-net
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
      - 5672:5672
      - 15672:15672

  client:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: client
    environment:
      - LOG_LEVEL=error
    volumes:
      - ./.data:/app/.data
      - ./.output:/app/.output
    networks:
      - money-laundering-analysis-net
    depends_on:
      - gateway
  
  query_1_filter:
    build:
      context: .
      dockerfile: src/cmd/node/Dockerfile
    container_name: query_1_filter
    environment:
      - LOG_LEVEL=debug
      - CONFIG_PATH=/app/config.yaml 
    volumes:
      - ./configs/query_1_filter.yaml:/app/config.yaml
    networks:
      - money-laundering-analysis-net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  money-laundering-analysis-net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
