name: money-laundering-analysis
services:
  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: gateway
    environment:
      - LOG_LEVEL=debug
      - ACCOUNTS_CONFIG_PATH=/app/accounts_queue_config.yaml
    volumes:
      - ./configs/account_queue_config.yaml:/app/accounts_queue_config.yaml
    networks:
      - money-laundering-analysis-net
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
      - RABBITMQ_LOG_LEVELS=error
    networks:
      - money-laundering-analysis-net
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
      - 5672:5672
      - 15672:15672

  client_1:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: client_1
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./.data:/app/.data
      - ./.output/client1:/app/.output
    networks:
      - money-laundering-analysis-net
    depends_on:
      - gateway

  query_2_cleaner_0:
    build:
      context: .
      dockerfile: src/cmd/node/Dockerfile
    container_name: query_2_cleaner_0
    environment:
      - LOG_LEVEL=debug
      - CONFIG_PATH=/app/config.yaml
      - WORKER_PREFIX=query_2_cleaner
      - ID=0
      - WORKER_AMOUNT=1
    volumes:
      - ./configs/q2/q2_cleaner.yaml:/app/config.yaml
    networks:
      - money-laundering-analysis-net
    depends_on:
      rabbitmq:
        condition: service_healthy

  query_2_router_0:
    build:
      context: .
      dockerfile: src/cmd/node/Dockerfile
    container_name: query_2_router_0
    environment:
      - LOG_LEVEL=debug
      - CONFIG_PATH=/app/config.yaml
      - WORKER_PREFIX=query_2_router
      - ID=0
      - WORKER_AMOUNT=1
      - NEXT_WORKER_AMOUNT=2
      - NEXT_WORKER_PREFIX=query_2_max
    volumes:
      - ./configs/q2/q2_router.yaml:/app/config.yaml
    networks:
      - money-laundering-analysis-net
    depends_on:
      rabbitmq:
        condition: service_healthy

  query_2_aggregator_0:
    build:
      context: .
      dockerfile: src/cmd/node/Dockerfile
    container_name: query_2_aggregator_0
    environment:
      - LOG_LEVEL=debug
      - CONFIG_PATH=/app/config.yaml
      - WORKER_PREFIX=query_2_max
      - ID=0
      - WORKER_AMOUNT=2
    volumes:
      - ./configs/q2/q2_aggregator.yaml:/app/config.yaml
    networks:
      - money-laundering-analysis-net
    depends_on:
      rabbitmq:
        condition: service_healthy

  query_2_aggregator_1:
    build:
      context: .
      dockerfile: src/cmd/node/Dockerfile
    container_name: query_2_aggregator_1
    environment:
      - LOG_LEVEL=debug
      - CONFIG_PATH=/app/config.yaml
      - WORKER_PREFIX=query_2_max
      - ID=1
      - WORKER_AMOUNT=2
    volumes:
      - ./configs/q2/q2_aggregator.yaml:/app/config.yaml
    networks:
      - money-laundering-analysis-net
    depends_on:
      rabbitmq:
        condition: service_healthy

  query_2_join:
    build:
      context: .
      dockerfile: src/cmd/node/Dockerfile
    container_name: query_2_join
    environment:
      - LOG_LEVEL=debug
      - CONFIG_PATH=/app/config.yaml
      - ACCOUNTS_CONFIG_PATH=/app/accounts_queue_config.yaml
      - WORKER_PREFIX=query_2_join
    volumes:
      - ./configs/q2/q2_join.yaml:/app/config.yaml
      - ./configs/account_queue_config.yaml:/app/accounts_queue_config.yaml
    networks:
      - money-laundering-analysis-net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  money-laundering-analysis-net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
