broker:
  type: e-e
  url: amqp://guest:guest@rabbitmq:5672/
  input: e_q4_agg
  output: e_q4_acc
  exchange_type: direct
  prefetch: 100
  durable: true
  auto_delete: false
  # exclusive: false
  no_wait: false
  internal: false

worker:
  type: "ScatterAndGather"
