broker:
  type: e-e
  input:
    exchange:
      name: e_q4_agg
      type: direct
    queue:
      name: q_q4_aggregator
      prefetch: 600
  output:
    exchange:
      name: e_q4_acc
      type: direct

worker:
  type: "ScatterAndGather"
  checkpoint_interval: 500
