broker:
  type: q-e
  input:
    queue:
      name: q_q4_router
  output:
    exchange:
      name: e_q4_agg
      type: direct

worker:
  type: "Spliter"
  params:
    field: 
      - "origin"
      - "dest"
  sync_eof:
    - retries_base_delay: 0.5
    - retries_step_delay: 0.5
    - max_retries: 5
