broker:
  type: q-q
  input:
    queue:
      name: q_q3_date_filter
  output:
    queue:
      name: q_q3_amount_filter

worker:
  type: "DateRangeFilter"
  params:
    type: "date_between"
    from: "2022/09/06"
    to: "2022/09/15"
  sync_eof:
    - retries_base_delay: 0.5
    - retries_step_delay: 0.5
    - max_retries: 5
