
broker:
  type: e-e
  url: amqp://guest:guest@rabbitmq:5672/
  input: e_entry
  input_queue: q_q345_filter
  output: e_q345_cleaner
  exchange_type: topic
  input_keys:
    - tx.*
  prefetch: 30
  durable: true
  auto_delete: false
  exclusive: false
  no_wait: false
  internal: false

worker:
  type: "DateRange"
  params:
    type: "date_between"
    from: "2023-01-01T00:00:00Z"
    to: "2023-12-31T23:59:59Z"
    # field: "Timestamp"
    # operator: "<"
    # value_float: 50.0
    # value_string: ""
  query: 345
  sync_eof:
    - retries_base_delay: 0.5
    - retries_step_delay: 0.5
    - max_retries: 5