broker:
  type: e-e
  input:
    exchange:
      name: e_entry
      type: topic
      keys:
        - tx.*
    queue:
      name: q_q345_filter
  output:
    exchange:
      name: e_q345_cleaner
      type: topic

worker:
  type: "DateRangeFilter"
  params:
    type: "date_between"
    from: "2022/09/01"
    to: "2022/09/06"
  sync_eof:
    - retries_base_delay: 0.5
    - retries_step_delay: 0.5
    - max_retries: 5
