accounts_dataset_path: "../.data/HI-Medium_accounts.csv"
transactions_dataset_path: "../.data/HI-Medium_Trans.csv"
output_path: "../.output"
transaction_batch_size: 500
account_batch_size: 500
server:
  host: "gateway"
  port: 8080
  connection_attempts: 5
  connection_attempt_delay_ms: 1000
