accounts_dataset_path: "../.data/LI-Small_accounts.csv"
transactions_dataset_path: "../.data/medium.csv"
# transactions_dataset_path: "../.data/LI-Small_Trans.csv"
output_path: "../.output"
transaction_batch_size: 100
account_batch_size: 100
server:
  host: "gateway"
  port: 8080
  connection_attempts: 5
  connection_attempt_delay_ms: 1000
