rabbitmq:
  type: q_q
  url: amqp://guest:guest@rabbitmq:5672/
  input_queue: input_queue
  output_queue: output_queue
  output_exchange: tx.usd
  exchange_type: direct
  routing_keys:
    - tx.usd
  prefetch: 30
  durable: true
  auto_delete: false
  exclusive: false
  no_wait: false
  internal: false

worker:
  type: SyncAmountFilter
  params:
    type: amount
    field: Amount
    operator: lt
    value_float: 50
