broker:
  type: q-e
  input:
    queue:
      name: query_results
  output:
    exchange:
      name: e_entry
      type: topic

server_host: "0.0.0.0"
server_port: 8080
checkpoint_interval: 100

monitoring:
  port: 9000
