worker:
  type: "Monitor"
monitor:
  udp_host: "0.0.0.0"
  udp_port: 9000
  heartbeat_timeout: "15s"
  check_interval: "5s"
  failure_threshold: 3
  restart_cooldown: "15s"
  rabbitmq_host: "rabbitmq"
  rabbitmq_port: 5672
