worker:
  type: "Monitor"
  params:
    bully:
      hosts:
        - "monitor_0"
        - "monitor_1"
        - "monitor_2"
      tcp_host: "0.0.0.0"
      tcp_port: 9001
      ping_interval: "1.5s"
      ping_timeout: "500ms"
    monitoring:
      udp_port: 9000
      ping_interval: "5s"
      ping_timeout: "2s"
      failure_threshold: 3
