broker:
  type: q-q
  url: amqp://guest:guest@rabbitmq:5672/
  input: q_q1_filter
  output: query_results
  exchange_type: direct
  prefetch: 300
  durable: true
  auto_delete: false
  exclusive: false
  no_wait: false
  internal: false

worker:
    type: "SyncFilter"
    params:
        type: "amount"
        field: "Amount"
        operator: "<"
        value_float: 50.0
        value_string: ""
    query: 1
