# q-e example (queue -> exchange)

broker:
  type: e-q
  url: amqp://guest:guest@rabbitmq:5672/
  input: e_entry
  output: q_q1_filter
  exchange_type: topic
  input_keys:
    - tx.usd
  prefetch: 30
  durable: true
  auto_delete: false
  exclusive: false
  no_wait: false
  internal: false

worker:
  type: Cleaner
  params:
    field:
      - "timestamp"
      - "format"
  query: 1

# Required envs if output_keys are omitted
# NEXT_WORKER_PREFIX=agg
# NEXT_WORKER_AMOUNT=2
# WORKER_PREFIX=tx_1
