broker:
    type: "q_q"
    url: "amqp://guest:guest@rabbitmq:5672/"
    input: "q_filter_in"
    output: "q_output"

worker:
    type: "SyncFilter"
    # config:
    params:
        type: "amount"
        field: "Amount"
        operator: "<"
        value_float: 50.0
        value_string: ""