broker:
    type: "q_q"
    url: "amqp://guest:guest@rabbitmq:5672/"
    input: "q_filter_in"
    output: "q_next_stage"

worker:
    type: "SyncFilter"
    # config:
    params:
        type: "amount"
        field: "Amount"
        operator: ">"
        value_float: 1000.0