workers:
    - query1_filter_0
    - query1_filter_1
    - query1_filter_2
    - query345_filter_0
    - query345_filter_1
    - query345_filter_2
    - query5_format_filter_0
    - query5_format_filter_1
    - query5_format_filter_2
    - query5_router_0
    - query5_router_1
    - query5_router_2
    - query5_converter_0
    - query5_converter_1
    - query5_converter_2
    - query5_amount_filter_0
    - query5_aggregator_0
