broker:
  type: q-e
  input:
    queue:
      name: q_q2_router
  output:
    exchange:
      name: e_q2_max
      type: direct

worker:
  type: "Router"
  params:
    field:
      origin: "BankID"
  sync_eof:
    - retries_base_delay: 0.5
    - retries_step_delay: 0.5
    - max_retries: 5
