broker:
  type: e-q
  input:
    exchange:
      name: e_entry
      type: topic
      keys:
        - tx.usd
    queue:
      name: q_q1_cleaner
  output:
    queue:
      name: q_q1_filter

worker:
  type: "Cleaner"
  params:
    field:
      - "timestamp"
      - "format"
  query: 1
  sync_eof:
    retries_base_delay: 0.5
    retries_step_delay: 0.5
    max_retries: 5
