broker:
  type: e-q
  input:
    exchange:
      name: e_q5_converter
      type: direct
  output:
    queue:
      name: q_q5_amount_filter

worker:
  type: "Converter"
  query: 5
  sync_eof:
    retries_base_delay: 0.5
    retries_step_delay: 0.5
    max_retries: 5
