broker:
  type: q-q
  url: amqp://guest:guest@rabbitmq:5672/
  input: q_q5_format_filter
  output: q_q5_router
  prefetch: 300
  durable: true
  auto_delete: false
  exclusive: false
  no_wait: false
  internal: false

worker:
  type: "SyncFilter"
  params:
    type: format
    field: Format
    operator: "=="
    value_float: 0.0
    value_string:
      - "Wire"
      - "ACH"
  query: 5
  sync_eof:
    - retries_base_delay: 0.5
    - retries_step_delay: 0.5
    - max_retries: 5
