# q-e example (queue -> exchange)

broker:
  type: q-e
  url: amqp://guest:guest@rabbitmq:5672/
  input: q_q5_router
  output: e_q5_converter
  exchange_type: direct
  # El routing key lo decide el worker (RoutingKey en el broker.Message)
  prefetch: 300
  durable: true
  auto_delete: false
  exclusive: false
  no_wait: false
  internal: false

worker:
  type: "Router"
  params:
    field:
      paid: "Currency"
  sync_eof:
    - retries_base_delay: 0.5
    - retries_step_delay: 0.5
    - max_retries: 5
